# Generated by Django 6.0.3 on 2026-03-21 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=50, unique=True, verbose_name='SKU / Código Interno'),
        ),
    ]
