# Generated by Django 5.2.12 on 2026-03-22 10:51

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0002_product_image_url_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSalesOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Número de Orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('paid', 'Pagada'), ('pending_delivery', 'Por Entregar'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Actualización')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Monto de Impuesto')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total a Pagar')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tasa de Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto de Descuento')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sales_rep', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Representante de Ventas')),
            ],
            options={
                'verbose_name': 'historical Orden de Venta',
                'verbose_name_plural': 'historical Órdenes de Venta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('paid', 'Pagada'), ('pending_delivery', 'Por Entregar'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Tasa de Impuesto (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Monto de Impuesto')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total a Pagar')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tasa de Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto de Descuento')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='customers.customer', verbose_name='Cliente')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Representante de Ventas')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Órdenes de Venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('yape', 'Yape'), ('plin', 'Plin')], default='cash', max_length=20, verbose_name='Método de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Nro. Operación')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalesOrderItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Línea')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product', verbose_name='Producto')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'historical Detalle de Venta',
                'verbose_name_plural': 'historical Detalles de Venta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('yape', 'Yape'), ('plin', 'Plin')], default='cash', max_length=20, verbose_name='Método de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Pago')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia/Nro. Operación')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.salesorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'historical Pago',
                'verbose_name_plural': 'historical Pagos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Línea')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='sales_sales_order_n_78c57a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', '-created_at'], name='sales_sales_custome_9034be_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['sales_rep', '-created_at'], name='sales_sales_sales_r_f56634_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', '-created_at'], name='sales_sales_status_d6b329_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='sales_order_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='sales_order_subtotal_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-payment_date'], name='sales_payme_order_i_372b86_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', '-payment_date'], name='sales_payme_payment_d0ecf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sales_order_item_unit_price_non_negative'),
        ),
    ]
